# This workflow keeps the repository active by creating a commit every 30 days.
name: keepalive
on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight on the first day of every month
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update timestamp
        run: |
          echo "Last keepalive: $(date)" > .keepalive
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .keepalive
          git commit -m "chore: keepalive"
          git push