name: Update Contra Google Calendars

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  scrape_and_update:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Run the script
      run: npm start
      env:
        GOOGLE_SERVICE_ACCOUNT_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
